version: "3.7"
services:
  postgres_canciones:
    image: "edwinc27/postgres-api-rest-canciones"
    ports:
      - 5432:5432
  app_canciones:
    image: "edwinc27/api-rest-canciones"
    ports:
      - 8080:8080
    depends_on:
      - postgres_canciones
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres_canciones:5432/canciones
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres